-- =========================================================================
-- Actualiza la ficha "hogar-venta" (v1.0) con el contenido del borrador
-- Ficha_Hogar_Seguro_Borrador.docx (13-ago-2026), armado a partir de datos
-- reales de ventas/instalaciones 2026 (scripts 549/200) y la estructura de
-- la ficha Comercio Seguro v1.1 como modelo.
--
-- Sigue siendo un BORRADOR: muchos campos quedan marcados [A completar]
-- para que el equipo comercial/instalaciones/precios los termine de cargar
-- directamente en el editor de fichas del portal (no hace falta re-correr
-- este script para esos ajustes).
--
-- Idempotente: UPDATE simple sobre la fila ya existente
-- (ficha_id='hogar-venta', version_key='v1.0'), creada por
-- seed_fichas_producto.sql. No inserta filas nuevas.
-- =========================================================================

begin;

update ficha_versiones set
  version_id   = 'V1.0',
  version_desc = 'Borrador — datos de ventas/instalaciones 2026 (13-ago-2026)',
  nombre       = 'SP Hogar Seguro — Venta',
  badge        = 'Hogar',
  version      = '0.1',
  fecha        = '13/08/2026',
  autor        = 'Borrador (scripts 549/200) — pend. revisión comercial/instalaciones/precios',
  general      = '{"descripcion":"Sistema de alarma monitoreada para el hogar, vendido en modalidad de venta directa del equipamiento (a diferencia de SP Comercio Seguro, que es en comodato); el cliente es propietario del equipo desde la instalación. Datos de venta e instalación del período analizado: 178 de 182 presupuestos ganados (98%) y 221 de 225 instalaciones reales fueron venta directa, sobre un total de 588 presupuestos cargados (31% de tasa de cierre). Conviven dos líneas de equipamiento bajo la categoría Netsuite ''Alarma Nueva'' (Hikvision AXPRO y Ajax) aún no formalizadas como kits oficiales — pendiente de definición por Producto.","infocards":[{"icon":"ti-home","title":"Cliente objetivo","body":"Viviendas particulares (casas y departamentos) — [A completar: zona de cobertura, ej. La Plata y Gran La Plata]"},{"icon":"ti-contract","title":"Plazo de contrato","body":"[A completar]"},{"icon":"ti-device-mobile","title":"Plataforma","body":"Doble ecosistema según instalación: App Hik-Connect (línea Hikvision AXPRO) o App Ajax Security (línea Ajax) — [A confirmar plataforma estándar recomendada por Producto]"}],"comercializacion":["Venta directa del equipamiento (título de propiedad del cliente) — a diferencia de SP Comercio Seguro, que es comodato","Cargo de instalación — [A completar: monto y política de bonificación]","Abono mensual de monitoreo (ABO-10 / ABO-16 en Netsuite) — presente en 88 y 44 de los 182 presupuestos ganados respectivamente [A confirmar cuál es el abono vigente / si son alternativos]","Adicional de abono 4G / Radio (ABO-11) cuando el domicilio no cuenta con línea fija o wifi estable — presente en 88 de 182 presupuestos ganados","Mano de obra de instalación: 2 técnicos en 114 de 182 casos (63%), 1 técnico en 38 casos (21%) — sugiere que la mayoría de las instalaciones requieren 2 técnicos","Servicios incluidos (instalación, monitoreo 24/7, notificación, control por App, botón de pánico, aviso corte de luz) tomados del Mapa de Servicios v1.4 — [A confirmar que coincide con lo comunicado hoy a clientes de Hogar Seguro]"],"checklist":[{"label":"Nombre","status":"rev"},{"label":"Alcance detallado","status":"rev"},{"label":"Preguntas Frecuentes","status":"rev"},{"label":"Contrato","status":"rev"},{"label":"Artículo en Netsuite","status":"prog"},{"label":"Material Marketing","status":"rev"},{"label":"Proceso Ventas","status":"rev"},{"label":"Proceso Instaladores","status":"rev"},{"label":"Proceso Operadores","status":"rev"},{"label":"Proceso Serv. Técnico","status":"rev"}]}'::jsonb,
  equipamiento = '{"kits":{"cols":["Componente","Línea Hikvision AXPRO","Línea Ajax"],"grupos":[{"label":"Componentes más frecuentes — Línea Hikvision AXPRO (de 182 presupuestos ganados)","filas":[["CEN019 Central Alarma Inalámbrica AXPRO Hikvision","48","—"],["SIR015 Sirena exterior Inalámbrica Hikvision","48","—"],["INF023 Infrarrojo Inalámbrico Hikvision","47","—"],["INF026 Infrarrojo exterior Inalámbrico Hikvision","36","—"],["MAG006 Magnético Inalámbrico AX Pro Hikvision","35","—"],["CRE010 Control Remoto Hikvision","35","—"],["SIR017 Sirena interior inalámbrica Hikvision AX Pro","28","—"],["TEC017 Teclado LED Inalámbrico Hikvision","23","—"]]},{"label":"Componentes más frecuentes — Línea Ajax (de 182 presupuestos ganados)","filas":[["SIR014 Sirena exterior Ajax","—","33"],["INF014 Infrarrojo Anti-mascota Ajax","—","31"],["INF018 Infrarrojo inalámbrico para exterior Ajax","—","26"],["MAG004 Magnético Inalámbrico Ajax","—","22"],["KIT-CTRAL24 Central Ajax + 2 MAG + 2 PIR + 1 SIR.INT + 2 C.REM","—","21"]]},{"label":"Común a ambas líneas","filas":[["MAG001 Magnético Común (69 casos, ambas líneas)","—","—"],["COM001 Comunicador 4G-MAX-T (29 casos, ambas líneas)","—","—"],["BAT002 Batería de Gel 7,5 Amp 12 Volt (19 casos, ambas líneas)","—","—"]]}]},"servicios":[{"icon":"ti-tool","label":"Instalación del sistema","desc":"En el domicilio del cliente"},{"icon":"ti-shield-check","label":"Monitoreo 24/7","desc":"Desde la central SP"},{"icon":"ti-bell","label":"Notificación inmediata","desc":"Ante cualquier evento"},{"icon":"ti-device-mobile","label":"Control desde la App","desc":"Armado/desarmado desde el celular"},{"icon":"ti-alert-octagon","label":"Botón de pánico","desc":"—"},{"icon":"ti-bolt","label":"Aviso ante corte de luz","desc":"—"}]}'::jsonb,
  precios      = '{"cards":[{"label":"Venta del equipo — línea Hikvision AXPRO","value":"$ —","sub":"Completar con precio vigente","featured":false},{"label":"Venta del equipo — línea Ajax","value":"$ —","sub":"Completar con precio vigente","featured":false},{"label":"Cargo de instalación","value":"$ —","sub":"Completar con precio vigente","featured":false},{"label":"Abono mensual de monitoreo","value":"$ —","sub":"Completar con precio vigente","featured":true,"featuredLabel":"Recurrente"},{"label":"Adicional 4G / Radio","value":"$ —","sub":"Completar con precio vigente","featured":false}],"alerta":"— Completar condiciones de ajuste de precios —","cancelacion":[{"momento":"[A completar]","penalidad":"[A completar — confirmar si aplica cancelación anticipada dado que no hay comodato de por medio, a diferencia de Comercio Seguro donde la penalidad está atada al contrato de comodato]"}],"notas":[{"icon":"ti-info-circle","color":null,"text":"Todos los montos de esta sección están pendientes de carga — ver borrador Ficha Hogar Seguro (13-ago-2026), sección 5."}]}'::jsonb,
  proceso      = '{"secciones":[{"label":"Ventas","pasos":[{"title":"Tipo de Proyecto en Netsuite: ''Alarma Nueva''","note":"Categoría con mayor volumen del sistema — 588 presupuestos en el período analizado"},{"title":"[A completar: pasos de carga de oportunidad, presupuesto, firma de contrato si aplica]","note":""}]},{"label":"Instalaciones","pasos":[{"title":"Asignación de mano de obra","note":"Predominan 2 técnicos (63% de los casos) — [A completar: criterio para asignar 1 vs 2 técnicos]"},{"title":"[A completar: checklist de instalación, alta en app, cierre de OV en Netsuite]","note":""}]}],"netsuite":[{"articulo":"Alarma Nueva (Tipo de Proyecto)","codigo":"—","desc":"Confirmado como categoría de mayor volumen — artículos específicos por línea aún sin formalizar como kit"}]}'::jsonb,
  faq          = '[{"q":"[A completar]","a":"Se sugiere adaptar la estructura de preguntas de la ficha de Comercio Seguro (activación/desactivación, batería, acceso a cámaras, tiempos de instalación, alta de usuarios) al escenario de venta directa, agregando: \"¿Qué pasa si el equipo se rompe estando fuera de garantía?\" — a diferencia de comodato, donde el reemplazo corre por cuenta de SP."}]'::jsonb,
  competencia  = '{"competidores":["901","Prosegur","ADT"],"filas":[{"criterio":"Equipamiento","sp":"[A completar]","valores":["[A completar]","[A completar]","[A completar]"]},{"criterio":"Venta / comodato","sp":"[A completar]","valores":["[A completar]","[A completar]","[A completar]"]},{"criterio":"Móvil Acuda propio","sp":"[A completar]","valores":["[A completar]","[A completar]","[A completar]"]},{"criterio":"Abono mensual","sp":"[A completar]","valores":["[A completar]","[A completar]","[A completar]"]},{"criterio":"Cargo instalación","sp":"[A completar]","valores":["[A completar]","[A completar]","[A completar]"]}],"nota":"Pendiente de completar — ver borrador Ficha Hogar Seguro, sección 9."}'::jsonb,
  areas        = '[{"area":"Ventas y Mktg","responsable":"—","comentarios":"—","estado":"rev","fecha":""},{"area":"Instalaciones","responsable":"—","comentarios":"—","estado":"rev","fecha":""},{"area":"Servicio Técnico","responsable":"—","comentarios":"—","estado":"rev","fecha":""},{"area":"Operadores","responsable":"—","comentarios":"—","estado":"rev","fecha":""},{"area":"Admin y Precios","responsable":"—","comentarios":"—","estado":"rev","fecha":""},{"area":"Facturación","responsable":"—","comentarios":"—","estado":"rev","fecha":""}]'::jsonb
where ficha_id = 'hogar-venta' and version_key = 'v1.0';

commit;

