-- Generado a partir de js/organigrama-data.js (fuente: Organigrama_SP_2025_1_0B.pptx)
-- Cargar DESPUES de crear la tabla areas (ver schema.sql)

insert into areas (id, nombre, parent_id, tipo, responsable, cargo) values
  ('directorio', 'Directorio', NULL, 'box', 'Fernando Ordoqui', 'Presidente'),
  ('gerencia-general', 'Gerencia General', 'directorio', 'box', 'Federico Ordoqui', 'Gerente General'),
  ('asesoria-legal', 'Asesoría Legal', 'gerencia-general', 'box', 'Externo', NULL),
  ('comite-ejecutivo', 'Comité Ejecutivo', 'gerencia-general', 'box', NULL, NULL),
  ('consultor-staff', 'Consultor Staff', 'gerencia-general', 'box', 'A. Petrikovich', NULL),
  ('admin-finanzas-ger', 'Administración y Finanzas', 'gerencia-general', 'box', 'Belén Amar', 'Gte. Admin. y Finanzas'),
  ('admin-finanzas', 'Admin y Finanzas', 'admin-finanzas-ger', 'box', 'M. L. Juliano', NULL),
  ('facturacion', 'Facturación', 'admin-finanzas', 'item', NULL, NULL),
  ('cobranzas', 'Cobranzas', 'admin-finanzas', 'item', NULL, NULL),
  ('pago-proveedores', 'Pago a Proveedores', 'admin-finanzas', 'item', NULL, NULL),
  ('atencion-cliente', 'Atención al Cliente', 'admin-finanzas', 'item', NULL, NULL),
  ('tesoreria', 'Tesorería', 'admin-finanzas', 'item', NULL, NULL),
  ('precios', 'Precios', 'admin-finanzas-ger', 'item', NULL, NULL),
  ('estudio-contable', 'Estudio Contable', 'admin-finanzas-ger', 'item', 'Externo', NULL),
  ('admin-rrhh', 'Admin. de RRHH', 'admin-finanzas-ger', 'item', NULL, NULL),
  ('ventas-marketing', 'Ventas y Marketing', 'gerencia-general', 'box', 'Federico Ordoqui', 'Gte. Ventas y Marketing'),
  ('ventas-sp', 'Ventas SP', 'ventas-marketing', 'box', 'Martin Ramos', NULL),
  ('vendedores-sp', 'Vendedores SP', 'ventas-sp', 'item', NULL, NULL),
  ('marketing', 'Marketing', 'ventas-marketing', 'box', 'Externo', NULL),
  ('proyectos-licitaciones', 'Proyectos Esp. y Licitaciones', 'ventas-marketing', 'box', 'Federico Ordoqui', NULL),
  ('vendedores-atempo', 'Vendedores Atempo', 'proyectos-licitaciones', 'item', NULL, NULL),
  ('preventa-sp', 'Preventa SP', 'proyectos-licitaciones', 'item', NULL, NULL),
  ('compras-operaciones', 'Compras y Operaciones Internas', 'gerencia-general', 'box', 'Gonzalo Ordoqui', 'Gte. Compras y Ops. Internas'),
  ('compras-deposito', 'Compras y Depósito', 'compras-operaciones', 'box', 'Gonzalo Ordoqui', NULL),
  ('operadores', 'Operadores', 'compras-operaciones', 'box', 'Orlando De la Serna', NULL),
  ('vigiladores-acuda', 'Vigiladores y Acuda', 'compras-operaciones', 'box', 'Osvaldo Suarez', NULL),
  ('mantenimiento-moviles', 'Mantenimiento Móviles', 'vigiladores-acuda', 'item', NULL, NULL),
  ('operaciones-tecnicas', 'Operaciones Técnicas', 'gerencia-general', 'box', 'Gonzalo Ordoqui', 'Gte. Operaciones Técnicas'),
  ('instalaciones', 'Instalaciones', 'operaciones-tecnicas', 'box', 'Eduardo / Walter', NULL),
  ('ampliaciones', 'Ampliaciones', 'operaciones-tecnicas', 'box', 'Federico Champané', NULL),
  ('operacion-tecnica-ampliaciones', 'Operación Técnica de Ampliaciones', 'ampliaciones', 'item', NULL, NULL),
  ('comunicaciones-renovacion-tecnologias', 'Comunicaciones y Renovación de Tecnologías', 'ampliaciones', 'item', NULL, NULL),
  ('servicio-tecnico', 'Servicio Técnico', 'operaciones-tecnicas', 'box', 'Alejandro Pesce', NULL),
  ('infraestructura-it', 'Infraestructura Tecnológica e Innovación', 'gerencia-general', 'box', 'Fernando Ordoqui', 'Gte. Inf. Tecnología e Innovación'),
  ('it-comunicaciones', 'Infraestructura y Tecnología en Comunicaciones', 'infraestructura-it', 'box', 'Gunther Block', NULL),
  ('soporte-it', 'Soporte de IT', 'it-comunicaciones', 'item', NULL, NULL),
  ('nuevas-tecnologias', 'Nuevas Tecnologías y Productos', 'infraestructura-it', 'box', 'Facundo Salas', NULL),
  ('operaciones-atempo', 'Operaciones Atempo', 'infraestructura-it', 'box', 'Fernando Ordoqui', NULL),
  ('teleasistentes-atempo', 'Teleasistentes Atempo', 'operaciones-atempo', 'item', NULL, NULL),
  ('instalador-atempo', 'Instalador Atempo', 'operaciones-atempo', 'item', NULL, NULL),
  ('procesos-mejora', 'Procesos y Mejora Continua', 'gerencia-general', 'box', 'Martin Wolcan', 'Gte. Procesos y Mejora Continua'),
  ('posventa-sp', 'Posventa SP', 'procesos-mejora', 'item', NULL, NULL)
on conflict (id) do update set
  nombre = excluded.nombre,
  parent_id = excluded.parent_id,
  tipo = excluded.tipo,
  responsable = excluded.responsable,
  cargo = excluded.cargo;
